version: "3.8"

networks:
    aquamanager-net: null

services:
    # Servicio proxy - filtro
    proxy:
        build:
            context: ./proxy
            dockerfile: dockerfile
        restart: unless-stopped
        expose:
            - "80/tcp"
        ports:
            - "80:80/tcp"
        logging:
            options:
                max-size: "100m"
                max-file: "3"
        networks:
            - aquamanager-net
        depends_on:
            # - aquamanager
            - contadores
            - personas

    # Servicio de front-end
    aquamanager:
        build:
            context: ./aquamanager
            dockerfile: dockerfile
        restart: unless-stopped
        networks:
            - aquamanager-net

    
    # Servicio de contadores
    contadores:
        build:
            context: ./contadores
            dockerfile: dockerfile
        restart: unless-stopped
        networks:
            - aquamanager-net

    # Servicio de personas
    personas:
        build:
            context: ./contadores
            dockerfile: dockerfile
        restart: unless-stopped
        networks:
            - aquamanager-net
