version: '3'
services:
  certbot:
    image: certbot/certbot
    ports:
      - "80:80/tcp"
    volumes:
      - ./certs:/etc/letsencrypt
    command: certonly --standalone -d aquamanager.ddns.net --non-interactive --agree-tos --email lcotley843@g.educaand.es
