version: "3.8"

networks:
    aquamanager-net: null

services:
    # Servicio proxy - filtro
    proxy:
        build:
            context: .
            dockerfile: proxy/dockerfile
        restart: unless-stopped
        expose:
            - "80/tcp"
        ports:
            - "8080:80/tcp"
        logging:
            options:
                max-size: "100m"
                max-file: "3"
        networks:
            - aquamanager-net
        depends_on:
            - contadores
            - personas
    
    # Servicio de contadores
    contadores:
        build:
            context: .
            dockerfile: contadores/dockerfile
        restart: unless-stopped
        expose:
            - "8080/tcp"
        networks:
            - aquamanager-net

    # Servicio de personas
    personas:
        build:
            context: .
            dockerfile: contadores/dockerfile
        restart: unless-stopped
        expose:
            - "8080/tcp"
        networks:
            - aquamanager-net
