version: "3.8"

volumes:
    contadores-db-data: null

networks:
    aquamanager-net: null

services:
    # Servicio proxy - filtro
    proxy:
        build:
            context: ./proxy
            dockerfile: dockerfile
        restart: unless-stopped
        expose:
            - "8080/tcp"
        ports:
            - "8080:80/tcp"
        logging:
            options:
                max-size: "100m"
                max-file: "3"
        networks:
            - aquamanager-net
        depends_on:
            # - aquamanager
            - contadores
            - personas

    # Servicio de front-end
    aquamanager:
        build:
            context: ./aquamanager
            dockerfile: dockerfile
        expose:
            - "80/tcp"
        ports:
            - "80:8080/tcp"
        restart: unless-stopped
        networks:
            - aquamanager-net
        environment:
            VUE_APP_BACKEND_API_BASE_URL: 192.168.1.128:8080
    
    # Servicio de contadores
    contadores:
        build:
            context: ./contadores
            dockerfile: dockerfile
        restart: unless-stopped
        networks:
            - aquamanager-net
        depends_on:
            - contadores-db
    
    # Base de datos de contadores
    contadores-db:
        image: mongo
        restart: unless-stopped
        logging:
            options:
                max-size: "100m"
                max-file: "3"
        expose:
            - "27017/tcp"
        networks:
            - aquamanager-net
        volumes:
            - "contadores-db-data:/data/db"
            - type: tmpfs
              target: /data/configdb
              tmpfs:
                  size: 10MB

    # Servicio de personas
    personas:
        build:
            context: ./contadores
            dockerfile: dockerfile
        restart: unless-stopped
        networks:
            - aquamanager-net
