version: "3.8"

volumes:
    contadores-db-data: null
    users-db-data: null
    lecturas-influxdb-data: null

networks:
    aquamanager-net: null

services:
    # Servicio proxy - filtro
    proxy:
        build:
            context: ./proxy
            dockerfile: dockerfile
        restart: unless-stopped
        expose:
            - "8080/tcp"
        ports:
            - "8080:443/tcp"
            # - "8080:80/tcp"
        logging:
            options:
                max-size: "100m"
                max-file: "3"
        networks:
            - aquamanager-net
        volumes:
            - ./proxy/apigateway/:/etc/nginx/conf.d/:ro
            - ./certs:/etc/letsencrypt
        depends_on:
            # - aquamanager
            - contadores
            - users

    # Servicio de front-end
    aquamanager:
        build:
            context: ./frontend/aquamanager
            dockerfile: dockerfile
        expose:
            - "80/tcp"
        ports:
            - "80:8080/tcp"
        restart: unless-stopped
        networks:
            - aquamanager-net
        environment:
            # VUE_APP_BACKEND_API_BASE_URL: https://localhost:8080
            VUE_APP_BACKEND_API_BASE_URL: https://aquamanager.ddns.net:8080
    
    # Servicio de contadores
    contadores:
        build:
            context: ./backend/contadores
            dockerfile: dockerfile
        restart: unless-stopped
        networks:
            - aquamanager-net
        environment:
            CONTADORES_DB: contadores-db
            LECTURAS_DB: lecturas-influxdb
        depends_on:
            - contadores-db
            - lecturas-influxdb
    
    # Base de datos de contadores
    contadores-db:
        image: mongo
        restart: unless-stopped
        logging:
            options:
                max-size: "100m"
                max-file: "3"
        expose:
            - "27017/tcp"
        networks:
            - aquamanager-net
        volumes:
            - "contadores-db-data:/data/db"
            - type: tmpfs
              target: /data/configdb
              tmpfs:
                  size: 10MB
                
    # Servicio de lecturas InfluxDB
    lecturas-influxdb:
        image: influxdb:1.8-alpine
        networks:
          - aquamanager-net
        volumes:
          - "lecturas-influxdb-data:/var/lib/influxdb"

    # Servicio de usuarios
    users:
        build:
            context: ./backend/users
            dockerfile: dockerfile
        restart: unless-stopped
        networks:
            - aquamanager-net
        environment:
            AUTH_DB: users-db
        depends_on:
            - users-db
    
    # Base de datos de contadores
    users-db:
        image: mongo
        restart: unless-stopped
        logging:
            options:
                max-size: "100m"
                max-file: "3"
        expose:
            - "27017/tcp"
        networks:
            - aquamanager-net
        volumes:
            - "users-db-data:/data/db"
            - type: tmpfs
              target: /data/configdb
              tmpfs:
                  size: 10MB
