FROM python:3.9-alpine

WORKDIR /app

RUN \
    apk add gcc musl-dev python3-dev libffi-dev openssl-dev cargo && \
    pip install --upgrade pip && \
    pip install wheel && \
    apk del gcc musl-dev python3-dev libffi-dev openssl-dev cargo

RUN addgroup -S cotelus && adduser -S cotelus -G cotelus
ENV PATH "$PATH:/home/cotelus/.local/bin"
USER cotelus

COPY --chown=cotelus:cotelus . .
RUN pip install -r requirements.txt

CMD ["gunicorn","core.prepare_service:prepare_service","--bind","0.0.0.0:8080","--worker-class","aiohttp.GunicornWebWorker"]
